// ng-todo/src/app/components/create-todo/create-todo.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ITodo } from '../../models/todo';
import { TodoService } from '../../services/todo.service';

@Component({
  selector: 'app-create-todo',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './create-todo.component.html',
  styles: ``,
})
export class CreateTodoComponent {
  @Output() createdEmit = new EventEmitter<void>();

  newTodo: ITodo = {
    id: 0,
    title: '',
    description: '',
    completed: false,
  };

  constructor(private todoService: TodoService) {}

  createTodo(): void {
    if (this.newTodo != null) {
      console.log('NOT NULL');
      if (this.newTodo.title != '' && this.newTodo.description != '') {
        this.todoService.createTodo(this.newTodo);
        this.newTodo.id = 0;
        this.newTodo.title = '';
        this.newTodo.description = '';
        this.createdEmit.emit();
      } else {
        alert('Please fill in all fields');
      }
    }
  }
}

<form #todoForm="ngForm" class="flex flex-col gap-y-3">
  <h3>Create todo</h3>

  <input
    type="text"
    name="title"
    placeholder="Title"
    required
    [(ngModel)]="newTodo.title"
  />
  <textarea
    name="description"
    cols="12"
    rows="5"
    placeholder="Description"
    [(ngModel)]="newTodo.description"
    required
  ></textarea>
  <button
    type="submit"
    (click)="createTodo()"
    class="text-white bg-primary rounded-sm p-3 mx-auto"
  >
    Add todo
  </button>
</form>

// react-todo/src/components/CreateTodo.tsx
import React, { useContext, useState } from "react";
import { ITodo } from "../models/todo";
import { createTodo, getTodos } from "../services/todoservice";
import { TodoContext } from "../App";

export default function CreateTodo() {
  const [todos, setTodos] = useContext(TodoContext);

  const [formData, setFormData] = useState<ITodo>({
    id: 0,
    title: "",
    description: "",
    completed: false,
  });

  function handleInputChange(
    event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) {
    const { name, value } = event.target;

    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  }

  function submitForm() {
    if (formData) {
      if (formData.title != "" && formData.description != "") {
        contextCreateTodo(formData);
        setFormData({
          id: 0,
          title: "",
          description: "",
          completed: false,
        });
      }
    }
  }

  function contextCreateTodo(todo: ITodo): void {
    createTodo(todo);
    setTodos(getTodos());
  }

  return (
    <form className="flex flex-col gap-y-3 w-full sm:w-1/3">
      <h3>Create todo</h3>
      <input
        type="text"
        name="title"
        placeholder="Title"
        value={formData.title}
        onChange={handleInputChange}
        required
      />
      <textarea
        name="description"
        cols={12}
        rows={5}
        placeholder="Description"
        required
        value={formData.description}
        onChange={handleInputChange}
      ></textarea>
      <button
        onClick={() => submitForm()}
        className="text-white bg-primary rounded-sm p-3 mx-auto"
      >
        Add todo
      </button>
    </form>
  );
}
