// react-todo/src/components/Footer.tsx
export default function Footer() {
  const currentDate: number = new Date().getFullYear();

  return (
    <footer className="bg-white flex flex-col justify-center items-center py-3">
      <h3 className="text-primary">Ng Todo</h3>
      <a href="https://azaber.com/" target="_blank" className="text-slate-600">
        Created by Azaber {currentDate}
      </a>
    </footer>
  );
}

// ng-todo/src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [],
  templateUrl: './footer.component.html',
  styles: ``,
})
export class FooterComponent {
  currentDate: number = new Date().getFullYear();
}

<footer class="bg-white flex flex-col justify-center items-center py-3">
  <h3 class="text-primary">Ng Todo</h3>
  <a href="https://azaber.com/" target="_blank" class="text-slate-600"
    >Created by Azaber {{ currentDate }}</a
  >
</footer>
